CRL support
deptofdefense/iceberg pull request #15
Opened 2020-09-02 14:04 UTC by pjdufour-dds

2020-09-03 22:16 UTC, chrisgilmerproj commented
I was reviewing this and running through the `Makefile` examples when I hit an error. I ran `rm -rf temp/ && make test_cli` and got this output:

```text
mkdir -p temp
openssl req -x509 -nodes -days 365 -newkey rsa:2048 -subj "/C=US/O=Atlantis/OU=Atlantis Digital Service/CN=icebergca" -keyout temp/ca.key -out temp/ca.crt
Generating a RSA private key
.....................................................................................................................................................+++++
...................................+++++
writing new private key to 'temp/ca.key'
-----
echo '01' > temp/ca.srl
touch temp/index.txt
echo 'unique_subject = yes' > temp/index.txt.attr
mkdir -p temp
openssl genrsa -out temp/server.key 2048
Generating RSA private key, 2048 bit long modulus (2 primes)
......................................................+++++
...........+++++
e is 65537 (0x010001)
openssl req -new -key temp/server.key -subj "/C=US/O=Atlantis/OU=Atlantis Digital Service/CN=iceberglocal" -out temp/server.csr
openssl ca -config examples/conf/openssl.cnf -batch -notext -in temp/server.csr -out temp/server.crt
Using configuration from examples/conf/openssl.cnf
Check that the request matches the signature
Signature ok
Certificate Details:
        Serial Number: 1 (0x1)
        Validity
            Not Before: Sep  3 22:11:23 2020 GMT
            Not After : Sep  3 22:11:23 2021 GMT
        Subject:
            countryName               = US
            organizationName          = Atlantis
            organizationalUnitName    = Atlantis Digital Service
            commonName                = iceberglocal
Certificate is to be certified until Sep  3 22:11:23 2021 GMT (365 days)

Write out database with 1 new entries
Data Base Updated
bash scripts/test-cli.sh
Using temporary directory at /var/folders/b5/2fhdzt3s19l41s4j63z1swjh0000gn/T/shunit.zyN6iB/tmp
Reading testdata from /Users/cgilmer/Projects/deptofdefense/iceberg/scripts/../testdata
testServe
ASSERT:unexpected output expected:<> but was:<iceberg: error initializing certificate revocation list: error loading CRL from file "temp/ca.crl.der": open temp/ca.crl.der: no such file or directory
Try iceberg --help for more information.>
shunit2:ERROR testServe() returned non-zero return code.
Tearing Down

Ran 1 test.

FAILED (failures=2)
Tearing Down
make: *** [test_cli] Error 1
```

Running `make crl` fixed this issue for me. I suggest one update in the `Makefile` on line 35 should be updated to this:

```make
test_cli: bin/iceberg temp/ca.crt temp/server.crt crl ## Run CLI tests
```

2020-09-03 22:22 UTC, chrisgilmerproj commented on cmd/iceberg/main.go
> +	}
What happens here if the format isn't recognized? It seems like it just continues but without loading anything from the file listed. Should there be an error in that case?

2020-09-03 22:37 UTC, chrisgilmerproj requested changes
I only see two small issues. One is a check on the crl format. The other is an issue with the makefile `test_cli` target. Otherwise this looks good to go.

2020-09-04 00:32 UTC, pjdufour-dds commented
I refactored the `crl` make target, so it is run with test_cli.  Added check with crl format.  Thanks for the review!

2020-09-04 15:05 UTC, chrisgilmerproj approved these changes
🚀

2020-09-04 19:18 UTC, merged